"""Versioned, checksummed authorization fixture matrix (SDK fixture ownership, §5.5).

``auth-sdk-m8`` is the single canonical owner of the shared role/flag/
decision/event test-fixture matrix. ``fastapi-m8`` and ``fa-auth-m8`` consume
it from this package's data; ``security-tests-m8`` vendors the same JSON so
the harness stays SDK-free. Every consumer verifies the schema version and the
checksum here rather than re-deriving its own expectations, so a hand-edited
or partially regenerated file fails loudly instead of silently drifting from
the canonical truth table.

The packaged file is regenerated by
``scripts/generate_authorization_fixture_matrix.py`` — never hand-edit it.
"""

from __future__ import annotations

import hashlib
import json
from importlib import resources
from typing import Any, Final

from auth_sdk_m8.core.exceptions import (
    FixtureChecksumMismatchError,
    UnsupportedFixtureMatrixSchemaVersionError,
)

#: Schema version of the fixture matrix this SDK release publishes.
FIXTURE_MATRIX_SCHEMA_VERSION: Final[str] = "1"

_DATA_PACKAGE: Final[str] = "auth_sdk_m8.testing"
_DATA_FILENAME: Final[str] = "authorization_matrix.json"
_CHECKSUM_KEY: Final[str] = "checksum_sha256"

#: Bounded, secret-free reason codes for the typed errors below.
UNSUPPORTED_FIXTURE_MATRIX_SCHEMA_VERSION_REASON = (
    "unsupported_fixture_matrix_schema_version"
)
FIXTURE_MATRIX_CHECKSUM_MISMATCH_REASON = "fixture_matrix_checksum_mismatch"


def _compute_checksum(payload: dict[str, Any]) -> str:
    """Deterministic sha256 over every field except the checksum itself."""
    body = {k: v for k, v in payload.items() if k != _CHECKSUM_KEY}
    canonical = json.dumps(body, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _parse_and_verify_fixture_matrix(raw: str) -> dict[str, Any]:
    """Parse *raw* JSON and enforce the schema-version/checksum guards.

    Split from :func:`load_authorization_fixture_matrix` so the verification
    logic is testable directly against arbitrary JSON text, without faking
    package-resource access.

    Raises:
        UnsupportedFixtureMatrixSchemaVersionError: If *raw* declares a schema
            version this SDK release does not implement.
        FixtureChecksumMismatchError: If *raw*'s content does not match its
            declared checksum (hand-edited or partially regenerated).
    """
    payload: dict[str, Any] = json.loads(raw)

    schema_version = payload.get("schema_version")
    if schema_version != FIXTURE_MATRIX_SCHEMA_VERSION:
        raise UnsupportedFixtureMatrixSchemaVersionError(
            UNSUPPORTED_FIXTURE_MATRIX_SCHEMA_VERSION_REASON
        )

    declared_checksum = payload.get(_CHECKSUM_KEY)
    actual_checksum = _compute_checksum(payload)
    if declared_checksum != actual_checksum:
        raise FixtureChecksumMismatchError(FIXTURE_MATRIX_CHECKSUM_MISMATCH_REASON)

    return payload


def load_authorization_fixture_matrix() -> dict[str, Any]:
    """Load, checksum-verify, and return the packaged fixture matrix.

    Reads the JSON packaged alongside this module (included in the built
    wheel/sdist as ordinary package data — no filesystem path assumptions),
    so it resolves correctly whether ``auth-sdk-m8`` is installed editable or
    from a distribution.

    Returns:
        The parsed fixture matrix: ``role_flag_matrix``, ``minimum_role_matrix``,
        ``session_revoked_events`` (v1/v2), and ``canonical_jwt_fixtures``
        (signed with the bundled trusted test key).

    Raises:
        UnsupportedFixtureMatrixSchemaVersionError: If the packaged file
            declares a schema version this SDK release does not implement.
        FixtureChecksumMismatchError: If the packaged file's content does not
            match its declared checksum (hand-edited or partially
            regenerated).
    """
    raw = resources.files(_DATA_PACKAGE).joinpath(_DATA_FILENAME).read_text("utf-8")
    return _parse_and_verify_fixture_matrix(raw)


__all__ = [
    "FIXTURE_MATRIX_CHECKSUM_MISMATCH_REASON",
    "FIXTURE_MATRIX_SCHEMA_VERSION",
    "UNSUPPORTED_FIXTURE_MATRIX_SCHEMA_VERSION_REASON",
    "load_authorization_fixture_matrix",
]
